# -*- coding: utf-8 -*-
"""Lin_regression_Diamonds.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104EFv-H8MbhYqxw3ibPe8u4JuIVZLkQS
"""

import pandas as pd
import seaborn as sns
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn import linear_model
import matplotlib.pyplot as plt

from sklearn.linear_model import LassoCV

"""https://www.kaggle.com/datasets/shivam2503/diamonds"""

data=sns.load_dataset("diamonds")

data.head(3)

data.shape

data.isna().sum(0)

data.describe()

data.head(5)

data["cut"].unique()

data["cut"].nunique()

data["color"].value_counts()

data.info()

categorial_features = [feature for feature in data.columns if type(feature) not in ["float64", "int64"]]

data_corr= data.select_dtypes(include ="number")

data_corr.corr()

sns.heatmap(data_corr.corr(), annot =True, cmap ="coolwarm", fmt ='.4g')

ohe= OneHotEncoder(drop='first')

data.info()

X_objects =data.select_dtypes('category')
x= ohe.fit(X_objects)

codes= ohe.transform(X_objects).toarray()

codes

features_names=ohe.get_feature_names_out(['cut', 'color', 'clarity'])
features_names

data_coded = pd.concat([data_corr, pd.DataFrame(codes, columns= features_names).astype(int)], axis=1)

data_coded

X= data_coded.drop('price',axis=1)
y= data['price']

np.random.seed(10)

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.3)

scaler =StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

print('MSE train:', mean_squared_error(y_train, lin_reg.predict(X_train)))
print('MSE test:', mean_squared_error(y_test, lin_reg.predict(X_test)))

coef_df = pd.DataFrame(lin_reg.coef_, index=X.columns, columns = ['coef'])

coef_df.sort_values(by=['coef'])

"""$$
\|y - X\hat{w}\|^2 + \alpha\sum_{i=1}^k|w_i|
$$

$$
\|y - X\hat{w}\|^2 + \alpha\|w\|^2
$$
"""

lasso =linear_model.Lasso(alpha=10)
lasso.fit(X_train, y_train)

print('mse train lasso', mean_squared_error(y_train, lasso.predict(X_train)))
print('mse test lasso', mean_squared_error(y_test, lasso.predict(X_test)))

ridge=linear_model.Ridge(alpha=10)
ridge.fit(X_train, y_train)

print('mse train ridge', mean_squared_error(y_train, ridge.predict(X_train)))
print('mse test ridge', mean_squared_error(y_test, ridge.predict(X_test)))

lasso_coef=pd.DataFrame(lasso.coef_, index=X.columns, columns=['coef'])
lasso_coef.sort_values(by=['coef'])

ridge_coef=pd.DataFrame(lasso.coef_, index=X.columns, columns=['coef2'])
ridge_coef.sort_values(by=['coef2'])

alphas=[0.01, 0.1, 10, 100]
lasso_euclid=[]
ridge_euclid=[]
for i in alphas:
  lasso= linear_model.Lasso(alpha=i)
  lasso.fit(X_train, y_train)
  lasso_euclid.append(np.linalg.norm(lasso.coef_))

lasso_euclid

alphas=[0.01, 0.1, 10, 100]
for i in alphas:
  ridge= linear_model.Ridge(alpha=i)
  ridge.fit(X_train, y_train)
  ridge_euclid.append(np.linalg.norm(ridge.coef_))

ridge_euclid

print("Lasso Euclidean norms:")
print()
for i in alphas:
    lasso = linear_model.Lasso(alpha = i)
    lasso.fit(X_train, y_train)
    lasso_euclid.append(np.linalg.norm(lasso.coef_))

print(lasso_euclid)

print('----------')
print("Ridge Euclidean norms:")
print()

for i in alphas:
    ridge = linear_model.Ridge(alpha = i)
    ridge.fit(X_train, y_train)
    ridge_euclid.append(np.linalg.norm(ridge.coef_))

print(ridge_euclid)

x = np.asarray(alphas)
Y1 = np.asarray(lasso_euclid).reshape(len(x), -1)
Y2 = np.asarray(ridge_euclid).reshape(len(x), -1)
y1 = Y1.mean(axis=1)
y2 = Y2.mean(axis=1)
e1 = Y1.std(axis=1)
e2 = Y2.std(axis=1)

fig, ax = plt.subplots(figsize=(6,4))
ax.errorbar(x, y1, yerr=e1, marker='o', label='Lasso')
ax.errorbar(x, y2, yerr=e2, marker='o', label='Ridge')

ax.grid(True)
ax.set_xlabel('alpha')
ax.set_ylabel('Euclidean norms')
ax.legend(loc='lower left', frameon=True)
plt.show()

reg = LassoCV(cv = 5, alphas = alphas, random_state = 0).fit(X_train, y_train)

reg_alph = reg.alphas_
array = reg.mse_path_

a=[]
for i in range(len(array)):
    m = np.mean(array[i])
    a.append(m)

d2 = {"MSE_2": pd.Series(a), "alpha_2": pd.Series(reg_alph)}
df2 = pd.DataFrame(d2)
print(df2)

lasso = linear_model.Lasso(alpha = 0.1)
lasso.fit(X_train, y_train)
print('MSE train:', mean_squared_error(y_train, lasso.predict(X_train)))

coef_df_lasso_CV = pd.DataFrame(lasso.coef_, index = X.columns, columns = ['coef_lasso_cv'])
coef_df_lasso_CV.sort_values(by=['coef_lasso_cv'])

print('MSE test:', mean_squared_error(y_test, lasso.predict(X_test)))